apps/home/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectField, BooleanField, SubmitField, FileField
from wtforms.validators import DataRequired, Optional

# Create Case Form

class CreateCaseForm(FlaskForm):
    case_name = StringField('Case name', validators=[DataRequired()])
    assigned_to = StringField('Analyst Name', validators=[DataRequired()])
    ticket_id = StringField('Optional', validators=[Optional()])
    description = TextAreaField('Case description', validators=[Optional()])
    case_priority = SelectField('Select Priority',
                        choices=[('', 'Select Priority'),
                                 ('1', 'Critical'),
                                 ('2', 'Hard'),
                                 ('3', 'Medium'),
                                 ('4', 'Low')],
                        validators=[DataRequired()])
    virustotal = BooleanField("VirusTotal", validators=[DataRequired()])
    anyrun = BooleanField("AnyRun", validators=[Optional()])
    hybridanalysis = BooleanField("Hybrid Analysis", validators=[Optional()])
    malwarebazaar = BooleanField("Malware Bazaar", validators=[Optional()])
    alienvault_otx = BooleanField("AlienVault OTX", validators=[Optional()])
    urlscan = BooleanField("URLHaus & URLScan", validators=[Optional()])
    submit = SubmitField("Create Now")


# Create Case Form

class CreateSettingsForm(FlaskForm):
    VTAPI = StringField('VirusTotal API', validators=[Optional()])
    HBAPI = StringField('Hybrid Analysis API', validators=[Optional()])
    MBAPI = StringField('Malware Bazaar API', validators=[Optional()])
    ARAPI = StringField('AnyRun API', validators=[Optional()])
    URLAPI = StringField('URLHaus API', validators=[Optional()])
    OTXAPI = StringField('AlienVault OTX API', validators=[Optional()])
    submit = SubmitField("Update Now")

class SubmissionForm(FlaskForm):
    file = FileField("Malware File", validators=[DataRequired()])
    hash = StringField('Malware hash', validators=[DataRequired()])
    url = StringField('Suspicious URL, IP', validators=[DataRequired()])
    pcap = FileField("PCAP File", validators=[DataRequired()])

apps/home/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix=''
)

apps/home/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

import re, os, json
from apps import db
from apps.home import blueprint
from flask import request, render_template, send_file, redirect, url_for
from flask_login import login_required, current_user
from jinja2 import TemplateNotFound
from apps.authentication.models import Cases, APIs, FileHash, URLIP, PCAPS
from apps.home.forms import CreateCaseForm, CreateSettingsForm, SubmissionForm
from apps.home.utils import file_scan, hash_scan, urlip_scan, malwarebazaar, hashid, PyJSON
from apps.home.pcap import Pcap
from werkzeug.utils import secure_filename
from psutil import virtual_memory

@blueprint.route('/index')
@login_required
def index():
    memory = virtual_memory().percent
    filehash = FileHash.query.filter_by(user_id=current_user.get_id()).order_by(FileHash.id.desc())
    urls = URLIP.query.filter_by(user_id=current_user.get_id(), data_type='url').order_by(URLIP.id.desc())
    ips = URLIP.query.filter_by(user_id=current_user.get_id(), data_type='ip').order_by(URLIP.id.desc())
    packets = PCAPS.query.filter_by(user_id=current_user.get_id()).order_by(PCAPS.id.desc())
    cases_count = Cases.query.filter_by(user_id=current_user.get_id()).count()
    return render_template('home/index.html', cases_count=cases_count, FileHash=filehash, urls=urls, ips=ips, packets=packets, memory=memory, segment='index')

@blueprint.route('/<template>')
@login_required
def route_template(template):

    try:

        if not template.endswith('.html'):
            template += '.html'

        # Detect the current page
        segment = get_segment(request)

        # Serve the file (if exists) from app/templates/home/FILE.html
        return render_template("home/" + template, segment=segment)

    except TemplateNotFound:
        return render_template('home/page-404.html'), 404

    except:
        return render_template('home/page-500.html'), 500

@blueprint.route('/newcase', methods=['GET', 'POST'])
@login_required
def newcase():
    create_case_form = CreateCaseForm(request.form)
    if request.method == "POST":

        case_name = request.form.get('case_name')
        # Check casename exists
        case = Cases.query.filter_by(case_name=case_name).first()
        if case:
            return render_template(
                'home/newcase.html',
                msg='That Case name already exists',
                success=False,
                form=create_case_form)
        
        # else we can create the case
        case = Cases(case_name=case_name,user_id=current_user.get_id())
        case.assigned_to = request.form.get('assigned_to')
        case.ticket_id = request.form.get('ticket_id')
        case.case_priority = request.form.get('case_priority')
        case.description = request.form.get('description')
        # Anti-Malware Engines
        case.virustotal = True if request.form.get('virustotal') == "y" else False
        case.anyrun = True if request.form.get('anyrun') == "y" else False
        case.hybridanalysis = True if request.form.get('hybridanalysis') == "y" else False
        case.malwarebazaar = True if request.form.get('malwarebazaar') == "y" else False
        case.alienvault_otx = True if request.form.get('alienvault_otx') == "y" else False
        case.urlscan = True if request.form.get('urlscan') == "y" else False

        db.session.add(case)
        db.session.commit()
        return redirect(url_for('home_blueprint.cases',case_id=case.id))
    else:
        return render_template('home/newcase.html', form=create_case_form)

@blueprint.route('/cases/<int:case_id>', methods=['GET', 'POST'])
@login_required
def cases(case_id):
    case = Cases.query.filter_by(id=case_id, user_id=current_user.get_id()).first_or_404()
    submission_form = SubmissionForm(request.form)
    APIKey = APIs.query.filter_by(user_id=current_user.get_id()).first()
    file_count = FileHash.query.filter_by(case_id=case_id, user_id=current_user.get_id(), data_type="file").count()
    hash_count = FileHash.query.filter_by(case_id=case_id, user_id=current_user.get_id(), data_type="hash").count()
    url_count = URLIP.query.filter_by(case_id=case_id, user_id=current_user.get_id(), data_type="url").count()
    ip_count = URLIP.query.filter_by(case_id=case_id, user_id=current_user.get_id(), data_type="ip").count()
    counter = PyJSON({'file': file_count, 'hash': hash_count, 'url': url_count, 'ip': ip_count})
    case.counter = counter

    if request.method == "POST":
        if 'submit_file' in request.form:
            if case.virustotal or case.hybridanalysis:
                # check if the post request has the file part
                # If the user does not select a file, the browser submits an empty file without a filename.
                if 'file' in request.files and request.files['file'].filename != "":
                    file = request.files['file']
                    filename = file.filename
                    file = file.read()
                    sha256 = hashid(file, hash_type="sha256")
                    sha1 = hashid(file, hash_type="sha1")
                    md5 = hashid(file, hash_type="md5")
                    result = file_scan(file, APIKey, filename, sha256)

                    if hasattr(result, 'code'):
                        return render_template(
                        "home/case.html",
                        case=case,
                        form=submission_form,
                        error=result
                        )
                    else:
                        submission = FileHash(user_id=current_user.get_id(), case_id=case.id)
                        submission.case_name = case.case_name
                        submission.priority = case.case_priority
                        submission.file_name = filename
                        submission.data_type = "file"
                        submission.sha256 = sha256
                        submission.sha1 = sha1
                        submission.md5 = md5
                        submission.analysis_id = result.id if hasattr(result, 'id') else None
                        submission.size = result.size if hasattr(result, 'size') else None
                        submission.type = result.type_tag if hasattr(result, 'type_tag') else None
                        submission.scan_status = result.status if hasattr(result, 'status') else "completed"
                        submission.malicious = result.stats['malicious'] if hasattr(result, 'stats') else result.last_analysis_stats['malicious']
                        
                        db.session.add(submission)
                        db.session.commit()
                        return render_template(
                            "home/case.html",
                            case=case,
                            form=submission_form,
                            result=result
                        )
                else:
                    return render_template(
                        "home/case.html",
                        case=case,
                        form=submission_form,
                        error=PyJSON({'code': 'FileSubmissionError', 'message': 'Please submit a valid request and use a valid file name.'})
                    )
            else:
                return render_template(
                    "home/case.html",
                    case=case,
                    form=submission_form,
                    error=PyJSON({'code': 'SandboxError', 'message': 'Please enable Virustotal or Hybrid-analysis and try again.'})
                )
            
        elif 'submit_hash' in request.form:
            if case.virustotal or case.malwarebazaar:
                hash = request.form.get('hash')
                result = hash_scan(hash, APIKey)

                if hasattr(result, 'code'):
                    return render_template(
                    "home/case.html",
                    case=case,
                    form=submission_form,
                    error=result
                    )
                else:
                    submission = FileHash(user_id=current_user.get_id(), case_id=case.id)
                    submission.case_name = case.case_name
                    submission.priority = case.case_priority
                    submission.file_name = result.names[0] if hasattr(result, 'names') else result.file_name
                    submission.data_type = "hash"
                    submission.sha256 = result.sha256 if hasattr(result, 'sha256') else result.sha256_hash
                    submission.sha1 = result.sha1 if hasattr(result, 'sha1') else result.sha1_hash
                    submission.md5 = result.md5 if hasattr(result, 'md5') else result.md5_hash
                    submission.analysis_id = result.sha256 if hasattr(result, 'sha256') else result.sha256_hash
                    submission.size = result.size if hasattr(result, 'size') else result.file_size
                    submission.type = result.type_tag if hasattr(result, 'type_tag') else result.file_type
                    submission.scan_status = result.status if hasattr(result, 'status') else "completed"
                    submission.malicious = result.stats['malicious'] if hasattr(result, 'stats') else 1
                    
                    db.session.add(submission)
                    db.session.commit()
                    return render_template(
                        "home/case.html",
                        case=case,
                        form=submission_form,
                        result=result
                    )
            else:
                return render_template(
                    "home/case.html",
                    case=case,
                    form=submission_form,
                    error=PyJSON({'code': 'SandboxError', 'message': 'Please enable Virustotal or Malware-Bazaar and try again.'})
                )
            
        elif 'submit_url' in request.form:

apps/templates/home/allcases.html
{% extends "layouts/base.html" %}

{% block title %} Total Cases {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<!-- data tables css -->
<link rel="stylesheet" href="/static/assets/css/plugins/dataTables.bootstrap4.min.css">
{% endblock stylesheets %}

{% block content %}

    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-content">
            <!-- [ breadcrumb ] start -->
            <div class="page-header">
                <div class="page-block">
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <div class="page-header-title">
                                <h5 class="m-b-10">Total Cases</h5>
                            </div>
                            <ul class="breadcrumb">
                                <li class="breadcrumb-item"><a href="/"><i class="feather icon-home"></i></a></li>
                                <li class="breadcrumb-item"><a href="{{ url_for('home_blueprint.allcases') }}">Investigation</a></li>
                                <li class="breadcrumb-item"><a href="{{ url_for('home_blueprint.allcases') }}">Total Cases</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- [ breadcrumb ] end -->
            <!-- [ Main Content ] start -->
            <div class="row">
                {% if msg %}
                    <div class="col-md-12">
                        <div class="alert alert-success" role="alert">
                            {{ msg | safe }}
                        </div>
                    </div>
                {% endif %}
                <!-- Customer overview start -->
                <div class="col-md-12">
                    <div class="card table-card">
                        <div class="card-body p-4"> <!-- pb-5 -->
                            <div class="dt-responsive table-responsive">
                                <table id="all-cases-table" class="table table-hover m-b-0">
                                    <thead>
                                        <tr>
                                            <th><span>Date</span></th>
                                            <th><span>Case Name <a class="help" data-toggle="popover" title="Popover title" data-content="And here's some amazing content. It's very engaging. Right?"><i class="feather icon-help-circle f-16"></i></a></span></th>
                                            <th><span>Created By <a class="help" data-toggle="popover" title="Popover title" data-content="And here's some amazing content. It's very engaging. Right?"><i class="feather icon-help-circle f-16"></i></a></span></th>
                                            <th><span>assigned To <a class="help" data-toggle="popover" title="Popover title" data-content="And here's some amazing content. It's very engaging. Right?"><i class="feather icon-help-circle f-16"></i></a></span></th>
                                            <th><span>Priority <a class="help" data-toggle="popover" title="Popover title" data-content="And here's some amazing content. It's very engaging. Right?"><i class="feather icon-help-circle f-16"></i></a></span></th>
                                            <th class="text-center"><span>Actions <a class="help" data-toggle="popover" title="Popover title" data-content="And here's some amazing content. It's very engaging. Right?"><i class="feather icon-help-circle f-16"></i></a></span></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for case in cases %}
                                        <tr>
                                            <td>{{ case.created_at }}</td>
                                            <td>
                                                <a href="{{ url_for('home_blueprint.cases',case_id=case.id) }}">{{ case.case_name }}</a>
                                            </td>
                                            <td>
                                                {{ current_user.username }}
                                            </td>
                                            <td>
                                                {{ case.assigned_to }}
                                            </td>
                                            <td>
                                                {% if case.case_priority == 1 %}
                                                    <div class="badge badge-light-danger">
                                                        Critical
                                                    </div>
                                                {% elif case.case_priority == 2 %}
                                                    <div class="badge badge-light-danger">
                                                        Hard
                                                    </div>
                                                {% elif case.case_priority == 3 %}
                                                    <div class="badge badge-light-warning">
                                                        Medium
                                                    </div>
                                                {% elif case.case_priority == 4 %}
                                                    <div class="badge badge-light-success">
                                                        Low
                                                    </div>
                                                {% endif %}
                                            </td>
                                            <td class="text-center">
                                                <i class="feather icon-eye text-primary m-r-5 f-20"></i>
                                                <a href="{{ url_for('home_blueprint.cases',case_id=case.id) }}" data-toggle="tooltip" data-placement="top" title="Edit">
                                                    <i class="feather icon-edit-2 text-success m-r-5 f-20"></i>
                                                </a>
                                                <a href="{{ url_for('home_blueprint.delete_case',case_id=case.id) }}" data-toggle="tooltip" data-placement="top" title="Delete">
                                                    <i class="feather icon-trash-2 text-danger m-r-5 f-20"></i>
                                                </a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Customer overview end -->
            </div>
            <!-- [ Main Content ] end -->
        </div>
    </div>
    <!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
	<!-- datatable Js -->
	<script src="/static/assets/js/plugins/jquery.dataTables.min.js"></script>
	<script src="/static/assets/js/plugins/dataTables.bootstrap4.min.js"></script>

    <script>
		$('#all-cases-table').DataTable({
            order: [[0, 'desc']],
        });
	</script>
{% endblock javascripts %}

apps/templates/home/newcase.html
{% extends "layouts/base.html" %}

{% block title %} New Case {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

	<!-- [ Main Content ] start -->
	<div class="pcoded-main-container">
		<div class="pcoded-content">
			<!-- [ breadcrumb ] start -->
			<div class="page-header">
				<div class="page-block">
					<div class="row align-items-center">
						<div class="col-md-12">
							<div class="page-header-title">
								<h5 class="m-b-10">New Case</h5>
							</div>
							<ul class="breadcrumb">
								<li class="breadcrumb-item"><a href="/"><i class="feather icon-home"></i></a></li>
								<li class="breadcrumb-item"><a href="{{ url_for('home_blueprint.newcase') }}">Investigation</a></li>
								<li class="breadcrumb-item"><a href="{{ url_for('home_blueprint.newcase') }}">New Case</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<!-- [ breadcrumb ] end -->
			<!-- [ Main Content ] start -->
			<form role="form" method="post" action="">
				{{ form.hidden_tag() }}
				<div class="row">
					<!-- [ New Case ] start -->
					{% if msg %}
						<div class="col-md-8">
							<div class="alert alert-danger" role="alert">
								{{ msg | safe }}
							</div>
						</div>
					{% endif %}
					<div class="col-md-8">
						<div class="card">
							<div class="card-header">
								<h5>Open new case</h5>
							</div>
							<div class="card-body">
								<div class="bt-wizard" id="progresswizard">
									<ul class="nav nav-pills nav-fill mb-3">
										<li class="nav-item"><a href="#progress-t-tab1" class="nav-link active" data-toggle="tab">General</a></li>
										<li class="nav-item"><a href="#progress-t-tab2" class="nav-link" data-toggle="tab">Details</a></li>
										<li class="nav-item"><a href="#progress-t-tab3" class="nav-link" data-toggle="tab">Final</a></li>
									</ul>
									<div id="bar" class="bt-wizard progress mb-3" style="height:6px">
										<div class="progress-bar bg-success" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 33.3333%;"></div>
									</div>
									<div class="tab-content">
										<div class="tab-pane show active" id="progress-t-tab1">
											<div class="form-group row">
												<label for="case_name" class="col-sm-3 col-form-label">Case Name <span class="text-danger">*</span></label>
												<div class="col-sm-9">
													{{ form.case_name(placeholder="Case name", class="form-control") }}
												</div>
											</div>
											<div class="form-group row">
												<label for="assigned_to" class="col-sm-3 col-form-label">Assigned to <span class="text-danger">*</span></label>
												<div class="col-sm-9">
													{{ form.assigned_to(placeholder="Analyst Name", class="form-control") }}
												</div>
											</div>
											<div class="form-group row">
												<label for="ticket_id" class="col-sm-3 col-form-label">Ticket ID</label>
												<div class="col-sm-9">
													{{ form.ticket_id(placeholder="Optional", class="form-control") }}
												</div>
											</div>
										</div>
										<div class="tab-pane" id="progress-t-tab2">
											<div class="form-group row">
												<label for="case_priority" class="col-sm-3 col-form-label">Case Priority <span class="text-danger">*</span></label>
												<div class="col-sm-9">
													{{ form.case_priority(class="form-control") }}
												</div>
											</div>
											<div class="form-group row">
												<label for="description" class="col-sm-3 col-form-label">Description <span class="text-danger">*</span></label>
												<div class="col-sm-9">
													{{ form.description(class="form-control", rows="3", spellcheck="false") }}
												</div>
											</div>
										</div>
										<div class="tab-pane" id="progress-t-tab3">
											<div class="text-center mt-2">
												<i class="feather icon-plus-square display-4 text-success"></i>
												<h5 class="mt-2">One more click! . .</h5>
												<p>Where you can submit new malware files, hashes, or URLs</p>
												{{ form.submit(class="btn btn-success") }}
											</div>
										</div>
										<div class="row justify-content-between btn-page">
											<div class="col-sm-6">
												<a href="javascript:;" class="btn btn-primary button-previous disabled">Previous</a>
											</div>
											<div class="col-sm-6 text-md-right">
												<a href="javascript:;" class="btn btn-primary button-next">Next</a>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-xl-3 col-md-6 mb-4">
						<h5>Anti-Malware Engines</h5>
						<hr>
						<div class="form-group mb-2">
							<div class="switch switch-primary d-inline m-r-10">
								{{ form.virustotal(class="form-control",checked="") }}
								<label for="virustotal" class="cr"></label>
							</div>
							<label>VirusTotal</label>
						</div>
						<div class="form-group mb-2">
							<div class="switch switch-primary d-inline m-r-10">
								{{ form.anyrun(class="form-control") }}
								<label for="anyrun" class="cr"></label>
							</div>
							<label>AnyRun</label>
						</div>
						<div class="form-group mb-2">
							<div class="switch switch-primary d-inline m-r-10">
								{{ form.hybridanalysis(class="form-control") }}
								<label for="hybridanalysis" class="cr"></label>
							</div>
							<label>Hybrid Analysis</label>
						</div>
						<div class="form-group mb-2">
							<div class="switch switch-primary d-inline m-r-10">
								{{ form.malwarebazaar(class="form-control") }}
								<label for="malwarebazaar" class="cr"></label>
							</div>
							<label>Malware Bazaar</label>
						</div>
						<div class="form-group mb-2">
							<div class="switch switch-primary d-inline m-r-10">
								{{ form.alienvault_otx(class="form-control") }}
								<label for="alienvault_otx" class="cr"></label>
							</div>
							<label>AlienVault OTX</label>
						</div>
						<div class="form-group mb-2">
							<div class="switch switch-primary d-inline m-r-10">
								{{ form.urlscan(class="form-control") }}
								<label for="urlscan" class="cr"></label>
							</div>
							<label>URLHaus & URLScan</label>
						</div>
					</div>
					<!-- [ New Case ] end -->
				</div>
			</form>
			<!-- [ Main Content ] end -->

		</div>
	</div>
	<!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script src="/static/assets/js/plugins/jquery.bootstrap.wizard.min.js"></script>
<script>
	$(document).ready(function() {
		$('#besicwizard').bootstrapWizard({
			withVisible: false,
			'nextSelector': '.button-next',
			'previousSelector': '.button-previous',
			'firstSelector': '.button-first',
			'lastSelector': '.button-last'
		});
		$('#btnwizard').bootstrapWizard({
			withVisible: false,
			'nextSelector': '.button-next',
			'previousSelector': '.button-previous',
			'firstSelector': '.button-first',
			'lastSelector': '.button-last'
		});
		$('#progresswizard').bootstrapWizard({
			withVisible: false,
			'nextSelector': '.button-next',
			'previousSelector': '.button-previous',
			'firstSelector': '.button-first',
			'lastSelector': '.button-last',
			onTabShow: function(tab, navigation, index) {
				var $total = navigation.find('li').length;
				var $current = index + 1;
				var $percent = ($current / $total) * 100;
				$('#progresswizard .progress-bar').css({
					width: $percent + '%'
				});
			}
		});
		$('#validationwizard').bootstrapWizard({
			withVisible: false,
			'nextSelector': '.button-next',
			'previousSelector': '.button-previous',
			'firstSelector': '.button-first',
			'lastSelector': '.button-last',
			onNext: function(tab, navigation, index) {
				if (index == 1) {
					if (!$('#validation-t-name').val()) {
						$('#validation-t-name').focus();
						$('.form-1').addClass('was-validated');
						return false;
					}
					if (!$('#validation-t-email').val()) {
						$('#validation-t-email').focus();
						$('.form-1').addClass('was-validated');
						return false;
					}
					if (!$('#validation-t-pwd').val()) {
						$('#validation-t-pwd').focus();
						$('.form-1').addClass('was-validated');
						return false;
					}
				}
				if (index == 2) {
					if (!$('#validation-t-address').val()) {
						$('#validation-t-address').focus();
						$('.form-2').addClass('was-validated');
						return false;
					}
				}
			}
		});
		$('#tabswizard').bootstrapWizard({
			'nextSelector': '.button-next',
			'previousSelector': '.button-previous',
		});
		$('#verticalwizard').bootstrapWizard({
			'nextSelector': '.button-next',
			'previousSelector': '.button-previous',
		});
	});
</script>
{% endblock javascripts %}

apps/templates/home/page-403.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Error 403 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- [ offline-ui ] start -->
    <div class="auth-wrapper maintance">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="text-center">
                        <!--  -->
                        <div class="">
                            <img src="/static/assets/images/maintenance/error.png" alt="" class="img-fluid">
                        </div>
                        <h5 class="mt-4">Access Denied - Please contact support.</h5>
                        <a href="/" class="btn btn-warning mb-4">
                            <i class="feather icon-info mr-2"></i>HOME
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- [ offline-ui ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/page-404.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Error 404 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- [ offline-ui ] start -->
    <div class="auth-wrapper maintance">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="text-center">
                        <!--  -->
                        <div class="">
                            <img src="/static/assets/images/maintenance/error.png" alt="" class="img-fluid">
                        </div>
                        <h5 class="mt-4">Oops! Page not found!</h5>
                        <a href="/" class="btn btn-warning mb-4">
                            <i class="feather icon-info mr-2"></i>HOME
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- [ offline-ui ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}